### ISSUE TITLE
ip2c not working...

### ISSUE THREAD

**Issue by snipiba** [rainlab/location-plugin#102]
If you can, replace ip2c.org with https://api.country.is/{$ip} instead

- used http protocol is unsafe `http://ip2c.org/?ip=....`
- ERR_ADDRESS_INVALID

**Comment by daftspunk** [comment]
LGTM!

**Comment by snipiba** [comment]
> LGTM!
are u sure? 
https://github.com/rainlab/location-plugin/blob/109744be8d49d004488afd26467873a3feab0f45/models/Country.php#L99

call to HTTP protocol? i know, is inside as a server request, but also... it can be https (if you wish to use ip2c.org)
`https://ip2c.org/?ip=...`

**Comment by daftspunk** [comment]
What you have suggested looks good. Make a pull request.

**Comment by snipiba** [comment]
> What you have suggested looks good. Make a pull request.

i was not sure, if you mean, that LGTM as a is working on your side, or accepted as solution ;)
i will fork and send PR
