### ISSUE TITLE
City Model

### ISSUE THREAD

**Issue by triasrahman** [rainlab/location-plugin#12]
It's very useful if you put the city model under the state model since city is mostly used for displaying location. If you want, I can contribute to this plugin.

Thanks,

**Comment by chesterx** [comment]
I need this too

**Comment by sajjad-ser** [comment]
+1

**Comment by daftspunk** [comment]
Can you provide more detail on what this would look like? Do you just want the model to exist, without seeding it? It could be a massive task to seed every city.

**Comment by vojtasvoboda** [comment]
Location Towns plugin waiting for approval, stay tuned I let you know! :-) I need it quick so I create plugin extending RainLab Location plugin.

**Comment by vojtasvoboda** [comment]
Location Towns plugin ready: [http://octobercms.com/plugin/vojtasvoboda-locationtown](http://octobercms.com/plugin/vojtasvoboda-locationtown). Let me know if it meets your needs, thanks.

**Comment by daftspunk** [comment]
Thanks @vojtasvoboda !
