### ISSUE TITLE
OctoberCMS marketplace update

### ISSUE THREAD

**Issue by ametad** [rainlab/location-plugin#17]
Hi Samuel,

Thank you for merging fixes into your plugin. Will you also 'push' these to the OctoberCMS marketplace (https://octobercms.com/plugin/rainlab-location)? I have the plugin attached to some of my projects and would like to take advantage of the fixes that are made.

Kind regards!

**Comment by daftspunk** [comment]
Thanks for your question. This will become available in the marketplace when the stable release is announced.
