### ISSUE TITLE
Bad request when used with reCaptcha

### ISSUE THREAD

**Issue by boogiestrat** [rainlab/location-plugin#23]
When you add a reCaptcha in the same form, the Ajax request gets refused by Google Validator. 
Returns status code : 406 Not Acceptable

and JSON response :
{result: "{"input_request":"g-recaptcha-response","message":"Select captcha"}"}

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by boogiestrat** [comment]
I a form I included the partial 'country-state' from the location plugin:
{% partial 'country-state' countryCode='' stateCode='' %}
Works like a charm.

Then, in the next div, I included the reCaptcha script as on Google's doc: 
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div class="g-recaptcha" data-sitekey="my_site_key"></div>

The captcha works fine, but the region dropdown isn't  dynamicaly populated anymore. 

From my inspector it returns these headers on the AJAX request:
Request Method:POST
Status Code:406 Not Acceptable

And instead of the countries / regions json response, it gives this response:
{"result":"{\"input_request\":\"g-recaptcha-response\",\"message\":\"Select captcha\"}"}

Hope it helps

**Comment by daftspunk** [comment]
This appears to be an issue with the implementation, the reCaptcha is interfering with a standard API call. It should be disabled for the `onGetCountryStates` AJAX handler. If the reCaptcha plugin is provided by another author, they may be able to assist with a solution or provide instructions on how to do this.
