### ISSUE TITLE
Upgrade location plugin to choose cities and allow user addition

### ISSUE THREAD

**Issue by SchneiderDe** [rainlab/location-plugin#31]
Hello,

Location plugin is great for countries and states. What about cities? It does not - currently - provide any solution.

**I suggest to provide a modification of this plugin for cities.**

Of course, the list of global cities could not be maintained in a single drop down! For this, my suggestion is as follows:

The should be a drop down of cities from the table cities. Based on the chosen country and state, there may be a few hundred getting dynamically populated in the drop down from the table cities.

Then, in the drop down, there should be a default "is_pinned" given as "city not listed here" . If the user chooses the value "city not listed here", A NEW TEXT FIELD SHOULD BE GENERATED (Ajax) in the <div> placeholder to allows an user to enter his choice of city that is not in the drop down.

Currently, a user directly inputs the city name as a string that is stored in the database. Thus, there is no city_id in there but only city_name.

If the user chooses a city, the value city_id > 0; and city_name = NULL;

If the choice is == "city not listed here", then the value of city_id = 0; and city_name = NameOfTheCity;

With this system, there is a possibility to dynamically grow the cities table, depending on each website and at the same time keeping the cities table small. Further, it also allows an admin to change the value of cities for a particular user at a later date by moving from the following:

city_name = NameOfTheCity ---> city_id = 215; // where 215 is the real value of that city

Like this, the table could be extended and more cities could be added.

If this feature is not implemented, certain things may remain inconsistent.

**Comment by LukeTowers** [comment]
Feel free to add this functionality in a PR and we'll probably merge it

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
