### ISSUE TITLE
issue with geocoding 

### ISSUE THREAD

**Issue by ah94med** [rainlab/location-plugin#32]
hello,
i encountered an issue working with the plugin and the geocoding from GoogleAPI, i was looking up countries using their names it was working fine until one of the entries was Palestine which is named "Palestinian territory, occupied" which doesn't exist on google API, so i renamed it to "Palestine" on my countries BD table and now it works fine.
P.S there is also a couple of states missing on the middle east area.

**Comment by LukeTowers** [comment]
Are you able to make a PR to solve this issue?

**Comment by ah94med** [comment]
yes. and i created it.

**Comment by LukeTowers** [comment]
Fixed by #37
