### ISSUE TITLE
Problem trying to render a partial with the countries and states

### ISSUE THREAD

**Issue by ribsousa** [rainlab/location-plugin#33]
I'm having a problem trying to render a partial with the countries and states on the front end as per plungin docs, [Front-end usage](http://octobercms.com/plugin/rainlab-location).

When I change the country in select it simply does not load the data with the country and states of it, it does not show any error.

See the pictures:

**Country and states render!**
![country and states render](http://iepm.online/storage/app/media/img1.png)

**Change country in select country and states not render!**
![change country in select country and states not render](http://iepm.online/storage/app/media/img2.png)

**Comment by LukeTowers** [comment]
Are you able to check the network tab of your devtools to see what the result of the AJAX request is when you change the country?

**Comment by ribsousa** [comment]
Json response!

![img](http://iepm.online/storage/app/media/json-response.jpg)

**Comment by LukeTowers** [comment]
Do you have a public URL I could try this out on?

**Comment by ribsousa** [comment]
You can register [here](http://iepm.online/en/login)

**Comment by rajakhoury** [comment]
@ribsousa  Same problem

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
