### ISSUE TITLE
Front end partial is not passing through selected countryId to the refreshed partial on country selection.

### ISSUE THREAD

**Issue by igneosaur** [rainlab/location-plugin#40]
I've extended the user plugin with a 'Profile' model with a few more fields (including the location fields) and a one-to-one relationship. I have a partial named 'country-state' with the following content:

    {% set countryId = countryId|default(form_value('profile[country_id]')) %}
    {% set stateId = stateId|default(form_value('profile[state_id]')) %}

    <div class="form-group">
        countryId: {{ countryId }}
        <label for="accountCountry">Country</label>
        {{ form_select_country('country_id', countryId, {
            id: 'accountCountry',
            class: 'form-control',
            emptyOption: 'Select country (optional)',
            'data-request': 'onInit',
            'data-request-update': {
                (__SELF__ ~ '::country-state'): '#partialCountryState'
            }
        }) }}
    </div>

    <div class="form-group">
        <label for="accountState">State</label>
        {{ form_select_state('state_id', countryId, stateId, {
            id: 'accountState',
            class: 'form-control',
            emptyOption: 'Select county/state (optional)'
        }) }}
    </div>

My partial is in the form like this:

    <div id="partialCountryState">
        {% partial '@country-state' countryId=user.profile.country_id stateId=user.profile.state_id %}
    </div>

It all renders correctly but when I select a country, the two dropdowns are empty and `countryId` is non-existent if I print it out.

**Comment by rajakhoury** [comment]
@igneosaur Same problem. Did you find out why ?

**Comment by igneosaur** [comment]
I didn't I'm afraid, I never got it to work with my `Profile` model. I had to have a huge rewrite and extend the user plugin a different way for it to work; Instead of extending with a new, separate, model with it's own table related to the users table (as described in [this tutorial](https://octobercms.com/support/article/ob-10)) I added fields directly to the user table and just did my stuff on the Users model (more like in [this tutorial](https://www.youtube.com/watch?v=AomK1eYAq78)). Plugin works fine with the latter method, but this still remains a bug for the former.

**Comment by rajakhoury** [comment]
@igneosaur I see, I guess it is Ok to do that. What you can do also, is use the google maps widget on the front end and let the user search of his location and auto fill the info ( Country, State, City, Street ect.. ) that's what I end up doing but also I had to modify the plugin's JS to parse additional location fields form google address object. ( e.g. Long Names ect.. )

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
