### ISSUE TITLE
How to get the NAME of the Country and State when sending a email Mail template

### ISSUE THREAD

**Issue by Hatalias** [rainlab/location-plugin#41]
I have a form where I use the Country and State fields of this plugin, when I send the form it takes the ID and not the name in mail template.

![captura de tela 2017-03-22 as 11 50 27](https://cloud.githubusercontent.com/assets/5147951/24204223/92b4230c-0ef6-11e7-8191-c23bf6670ba8.jpg)
![captura de tela 2017-03-22 as 11 50 39](https://cloud.githubusercontent.com/assets/5147951/24204224/92efd6cc-0ef6-11e7-9fda-53369613e5c6.jpg)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
