### ISSUE TITLE
Front-End Dropdown Value Code, Not ID #

### ISSUE THREAD

**Issue by coycash** [rainlab/location-plugin#45]
I need to pass the country and state name to a process once a front-end form is submitted, but I am given the country and state IDs (ie 3 and 4) instead of the codes (ie US and Nebraska).   Is there a conversion I can use?

**Comment by coycash** [comment]
Nevermind, just used a statement like:

`Country::find(4)->code`

**Comment by StanleyBonhomme** [comment]
@coycash  How did you exactly do this?
