### ISSUE TITLE
Howto make addressfinder to populate country and state dropdown

### ISSUE THREAD

**Issue by Alex360hd** [rainlab/location-plugin#47]
Hello,

I'm creating a plugin based on the location plugin.

I could successfully create my different address fields (street, zip, city, etc...) with country and state as a relation provided by this plugin. Everything works well.

Now I would like to add the addressfinder widget on the top of my form to automatically populate all the fields if you find an address using this widget.

It works for all textfield elements, but not with the country and state dropdown. How can I fix that ?

Thanks

**Comment by Alex360hd** [comment]
I made some more tests and it can work if you use textfield instead of dropdown for country and state. With standard textfield, the addressfinder is able to populate them.

But it seems there is a bug with the state field that is populated with the full state name instead of the state code.

For example, if I choose an address in France, it populate the country field with the country code : "FR", but the state code is "Bourgogne Franche-Comté" instead of "BFC" which break the relation with the state model.

**Comment by LukeTowers** [comment]
Feel free to dig more into this issue and make a PR that would fix it! :)

**Comment by w20k** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
