### ISSUE TITLE
United Kingdom Incomplete

### ISSUE THREAD

**Issue by eddieishere** [rainlab/location-plugin#49]
The whole of the UK is not included in the database. Northern Ireland is completely missing, only England, Scotland and Wales are included. Means that this plugin in its current state is unusable.

**Comment by LukeTowers** [comment]
@eddieishere feel free to make a pull request to add them

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
