### ISSUE TITLE
Call to undefined method `RainLab\Location\FormWidgets\AddressFinder::getParentForm()

### ISSUE THREAD

**Issue by shiftaltd** [rainlab/location-plugin#60]
On a fresh october installation, The widget gives me this error.

> Call to undefined method `RainLab\Location\FormWidgets\AddressFinder::getParentForm()

I'm the only one with this issue ?

**Comment by LukeTowers** [comment]
You require Build 447, which isn't released yet. Should be out in the next week or so, or you could switch to using composer and load the dev branch instead.

**Comment by shiftaltd** [comment]
Thanks. it works. But i'm not shure it's a good practice to

**Comment by LukeTowers** [comment]
You're correct, it's not. For some reason this plugin didn't have test updates enabled in the marketplace, I've corrected that.

**Comment by bennothommo** [comment]
Build 447 is out now, which should resolve this issue. Please feel free to re-open if this is not the case.
