### ISSUE TITLE
Migration for other countires. Are they required?

### ISSUE THREAD

**Issue by grafxflow** [rainlab/location-plugin#68]
This is more a question of are migrations needed for the other country states/districts etc?

I have been going through the epic task of getting all the existing countires states/districts from wikipedia (ISO_3166-2:??). Would anybody want me to create migrations for this plugin?

**Only issue I can see if anybody has already been adding them manually - there will be conflict with existing records id's etc**

**Comment by LukeTowers** [comment]
@grafxflow people tend to add them when they need them, as long as you add them to https://github.com/rainlab/location-plugin/blob/master/updates/seed_all_tables.php then it should be fine as existing installations won't use that seeder again as it's already been run while new installations will use it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
