### ISSUE TITLE
Undefined index: state_id

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/location-plugin#76]
I am trying to create a model which implement Location
```php
$address = new Address;
$address->name = "test";
$address->city = "Singapore";
// $address->state = null;
// $address->state_code = null;
$address->state_id = null;
$address->country_code = "SG";
$address->save();
```

and I just get this error in the console `Undefined index: state_id`

any idea please?

**Comment by LukeTowers** [comment]
@chrisvidal do you have a stack trace?

**Comment by LukeTowers** [comment]
Also what does your model look like?

**Comment by chrisvidal** [comment]
sorry for the trouble, it is working fine, something was wrong later in my code.
closing
