### ISSUE TITLE
Shipping Fee table doesn't exist

### ISSUE THREAD

**Issue by DavidBustillo** [rainlab/location-plugin#83]
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'shipping_fee' in 'field list' (SQL: update `rainlab_location_countries` set `is_enabled` = 0, `shipping_fee` = 100.09 where `id` = 1)" on line 669 of /home/hospit/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by daftspunk** [comment]
Hello @DavidBustillo ,

`shipping_fee` is not a column that is used by this plugin. It would appear that another plugin has introduced this column by extending the location plugin. The other plugin has not correctly added the column to the database and therefore this error occurs.

Please check your codebase for the `shipping_fee` attribute to determine which plugin is using it. Then follow up with the author of this plugin to confirm how to solve it.
