### ISSUE TITLE
Add the ability to search by establishment names

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/location-plugin#84]
Hi Samuel,

I was wondering wether we could [change this one line](https://github.com/rainlab/location-plugin/blob/aadecfb9c038060302845082cd3ff6b076cec6f7/formwidgets/addressfinder/assets/js/location-autocomplete.js#L75) to the following:

    types: ['geocode','establishment']

This way, we could also search by establishment name. This would make sense because sometimes you don't know the address of the place you're looking up the address for, and by entering the name of the venue, the address would appear automatically.

Taking this one step further would be to add a mappable field for the establishment name (like country, country-long... etc). 
Would you consider this if I do a pull request?

Thanks in advance.

**Comment by daftspunk** [comment]
Hey @maartenmachiels 

Added this in f28339d26f9a4fd613c80653ce5b7c90bd78852d

Yes, a PR for the additionally mapped fields is fine

Thanks!
