### ISSUE TITLE
Implement i18n support

### ISSUE THREAD

**Issue by tplessis** [rainlab/location-plugin#9]
Countries and states seeding are only in english.

**Comment by tplessis** [comment]
Hi,
Maybe a possible integration : https://github.com/MenaraSolutions/geographer
I'll look into soon.

**Comment by LukeTowers** [comment]
@tplessis Closing this for now, feel free to open a PR to solve this.

**Comment by mosid** [comment]
@tplessis Why not using the  translate plugin conditional extending with it?
```PHP    
     public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];
     public $translatable = ['name'];
```

**Comment by LukeTowers** [comment]
As above, make a PR detailing what you'd like changed and why and I'll review it :)
