### ISSUE TITLE
October repository gateway issue

### ISSUE THREAD

**Issue by dariopetraroia** [rainlab/location-plugin#91]
Hy, can you fix this please:

Problem 1
    - Root composer.json requires rainlab/location-plugin v1.2.1.1, it is found rainlab/location-plugin[v1.2.1.1] in the lock file and rainlab/location-plugin[dev-master, v1.0.8, ..., v1.2.2] from composer repo (https://gateway.octobercms.com) but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one from the lock file.

**Comment by daftspunk** [comment]
Hi Dario. Try updating the package manually. 

php artisan plugin:install RainLab.Location

**Comment by dariopetraroia** [comment]
Works, thank you!
