### ISSUE TITLE
Missing callback

### ISSUE THREAD

**Issue by Pixinside** [rainlab/location-plugin#99]
I've got this issue with the widget to autocomplete the location:

Loading the Google Maps JavaScript API without a callback is not supported: 
https://developers.google.com/maps/documentation/javascript/url-params#required_parameters

in /formwidgets/AddressFinder.php line 119

this:        
` $this->addJs('//maps.googleapis.com/maps/api/js?libraries=places&key='.$apiKey);`

should be:

`$this->addJs('//maps.googleapis.com/maps/api/js?libraries=places&key='.$apiKey.'&callback=initMap');`

**Comment by daftspunk** [comment]
Thanks!

Fixed in v1.2.5
